os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
env:
  - SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2016-05-31-a
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install mecab libmecab-dev mecab-ipadic-utf8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mecab mecab-ipadic; fi
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - make
  - make test
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -workspace OSX\ Projects/MeCab.xcworkspace -scheme MeCab build test ; fi
  